//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1/wsdl/", ConfigurationName="EventService.EventPortType")]
    public interface EventPortType
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string[]), Action="", Name="FaultException", Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EventService.EventResponse> EventAsync(EventService.EventRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
    public partial class HeaderType
    {
        
        private string identityField;
        
        private string clientTimeZoneIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string ClientTimeZoneID
        {
            get
            {
                return this.clientTimeZoneIDField;
            }
            set
            {
                this.clientTimeZoneIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
    public partial class DataItemResponseType
    {
        
        private object itemField;
        
        private DataItemResponseTypeName nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Float", typeof(Float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Int", typeof(Int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("String", typeof(String), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataItemResponseTypeName name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
    public partial class Float
    {
        
        private double valField;
        
        private bool valFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValSpecified
        {
            get
            {
                return this.valFieldSpecified;
            }
            set
            {
                this.valFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
    public partial class Int
    {
        
        private long valField;
        
        private bool valFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValSpecified
        {
            get
            {
                return this.valFieldSpecified;
            }
            set
            {
                this.valFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
    public partial class String
    {
        
        private string valField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
    public enum DataItemResponseTypeName
    {
        
        /// <remarks/>
        Application_Number,
        
        /// <remarks/>
        Score,
        
        /// <remarks/>
        Score_Category,
        
        /// <remarks/>
        Results,
        
        /// <remarks/>
        Scheme_Code,
        
        /// <remarks/>
        Score_Credit_Limit,
        
        /// <remarks/>
        STATUSCODE,
        
        /// <remarks/>
        STATUSDESC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
    public partial class HeaderResponseType
    {
        
        private string correlationIdField;
        
        private string startTimeField;
        
        private string completionTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CorrelationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CompletionTime
        {
            get
            {
                return this.completionTimeField;
            }
            set
            {
                this.completionTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
    public partial class DataItemType
    {
        
        private object itemField;
        
        private DataItemTypeName nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(DateTime), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Float", typeof(Float), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Int", typeof(Int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("String", typeof(String), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataItemTypeName name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
    public partial class DateTime
    {
        
        private System.DateTime valField;
        
        private bool valFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValSpecified
        {
            get
            {
                return this.valFieldSpecified;
            }
            set
            {
                this.valFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")]
    public enum DataItemTypeName
    {
        
        /// <remarks/>
        Application_Number,
        
        /// <remarks/>
        Request_Limit,
        
        /// <remarks/>
        Application_ID,
        
        /// <remarks/>
        Product,
        
        /// <remarks/>
        Credit_Card_Type,
        
        /// <remarks/>
        Promo_Code,
        
        /// <remarks/>
        Age,
        
        /// <remarks/>
        Resident_Type,
        
        /// <remarks/>
        Marital_Status,
        
        /// <remarks/>
        Address_Type,
        
        /// <remarks/>
        State,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Number_of_Dependents,
        
        /// <remarks/>
        Number_of_Children,
        
        /// <remarks/>
        Occupation_Type,
        
        /// <remarks/>
        Industry,
        
        /// <remarks/>
        Nature_of_Business,
        
        /// <remarks/>
        SubIndustry,
        
        /// <remarks/>
        Company_Type,
        
        /// <remarks/>
        Employment_type,
        
        /// <remarks/>
        Employment_Status,
        
        /// <remarks/>
        Employment_From,
        
        /// <remarks/>
        Years_In_Job,
        
        /// <remarks/>
        Employment_Location,
        
        /// <remarks/>
        Gross_Monthly_Income,
        
        /// <remarks/>
        Missing_Information,
        
        /// <remarks/>
        Employer_Status,
        
        /// <remarks/>
        Employer_Establish_Day,
        
        /// <remarks/>
        Annual_Net_Income,
        
        /// <remarks/>
        Annual_Gross_Income,
        
        /// <remarks/>
        Income_From_Other_Sources,
        
        /// <remarks/>
        Card_Limit,
        
        /// <remarks/>
        Card_Expiry,
        
        /// <remarks/>
        PCB_Response_XML,
        
        /// <remarks/>
        Maximum_Worststatus,
        
        /// <remarks/>
        Result,
        
        /// <remarks/>
        No_of_Contract,
        
        /// <remarks/>
        Results_2,
        
        /// <remarks/>
        Amount_of_Unpaid_Due_Installments,
        
        /// <remarks/>
        Overdue_Not_Paid_Amount,
        
        /// <remarks/>
        Total_Current_Overdue_Amount,
        
        /// <remarks/>
        Results_3,
        
        /// <remarks/>
        Number_of_Bank_Relationship,
        
        /// <remarks/>
        No_of_Installment_Loans,
        
        /// <remarks/>
        Total_Outstanding_Balances,
        
        /// <remarks/>
        No_of_Credit_Cards,
        
        /// <remarks/>
        Total_Credit_Limit,
        
        /// <remarks/>
        Total_Oustanding_Balance_1,
        
        /// <remarks/>
        No_Overdraft,
        
        /// <remarks/>
        Total_Credit_Limit_1,
        
        /// <remarks/>
        Total_Monthly_Payment_Excluding_Overdraft,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Event", WrapperNamespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1", IsWrapped=true)]
    public partial class EventRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1", Order=0)]
        public EventService.HeaderType Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Data", IsNullable=false)]
        public EventService.DataItemType[] Body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        public EventRequest()
        {
        }
        
        public EventRequest(EventService.HeaderType Header, EventService.DataItemType[] Body, string name)
        {
            this.Header = Header;
            this.Body = Body;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EventResponse", WrapperNamespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1", IsWrapped=true)]
    public partial class EventResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1", Order=0)]
        public EventService.HeaderResponseType Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Data", IsNullable=false)]
        public EventService.DataItemResponseType[] Body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        public EventResponse()
        {
        }
        
        public EventResponse(EventService.HeaderResponseType Header, EventService.DataItemResponseType[] Body, string name)
        {
            this.Header = Header;
            this.Body = Body;
            this.name = name;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface EventPortTypeChannel : EventService.EventPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class EventPortTypeClient : System.ServiceModel.ClientBase<EventService.EventPortType>, EventService.EventPortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EventPortTypeClient() : 
                base(EventPortTypeClient.GetDefaultBinding(), EventPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EventPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(EventPortTypeClient.GetBindingForEndpoint(endpointConfiguration), EventPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EventPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EventPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EventService.EventResponse> EventAsync(EventService.EventRequest request)
        {
            return base.Channel.EventAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EventPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EventPort))
            {
                return new System.ServiceModel.EndpointAddress("https://sasappvaartest01.vietcredit.com.vn:8343/RTDM/Event");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EventPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.EventPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EventPortTypeClient.GetEndpointAddress(EndpointConfiguration.EventPort);
        }
        
        public enum EndpointConfiguration
        {
            
            EventPort,
        }
    }
}
